jobs:
  test-group-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: "\n                    python -m pip install --upgrade pip\n          \
        \          pip install pytest\n                    pip install -r requirements.txt\n\
        \                    "
    - name: Run tests for job 1
      run: pytest tests/test_math_1.py tests/test_math_5.py
  test-group-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: "\n                    python -m pip install --upgrade pip\n          \
        \          pip install pytest\n                    pip install -r requirements.txt\n\
        \                    "
    - name: Run tests for job 2
      run: pytest tests/test_math_2.py tests/test_math_6.py
  test-group-3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: "\n                    python -m pip install --upgrade pip\n          \
        \          pip install pytest\n                    pip install -r requirements.txt\n\
        \                    "
    - name: Run tests for job 3
      run: pytest tests/test_math_3.py tests/test_math_7.py
  test-group-4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: "\n                    python -m pip install --upgrade pip\n          \
        \          pip install pytest\n                    pip install -r requirements.txt\n\
        \                    "
    - name: Run tests for job 4
      run: pytest tests/test_math_4.py tests/test_math_8.py
name: Parallel Tests
'on':
- push
- pull_request
