jobs:
  test-group-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - id: cached-poetry-dependencies
      name: Load cached venv
      uses: actions/cache@v3
      with:
        key: venv-{"runner.os"}-{"steps.setup-python.outputs.python-version"}-{"hashFiles("**/poetry.lock")}
        path: .venv
    - if: steps.cached-poetry-dependencies.outputs.cache-hit != "true"
      name: Install dependencies
      run: poetry install --no-interaction --no-root
    - name: Install project
      run: poetry install --no-interaction
    - name: Run tests for job 1
      run: poetry run pytest tests/test_math.py
  test-group-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - id: cached-poetry-dependencies
      name: Load cached venv
      uses: actions/cache@v3
      with:
        key: venv-{"runner.os"}-{"steps.setup-python.outputs.python-version"}-{"hashFiles("**/poetry.lock")}
        path: .venv
    - if: steps.cached-poetry-dependencies.outputs.cache-hit != "true"
      name: Install dependencies
      run: poetry install --no-interaction --no-root
    - name: Install project
      run: poetry install --no-interaction
    - name: Run tests for job 2
      run: 'poetry run pytest '
  test-group-3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - id: cached-poetry-dependencies
      name: Load cached venv
      uses: actions/cache@v3
      with:
        key: venv-{"runner.os"}-{"steps.setup-python.outputs.python-version"}-{"hashFiles("**/poetry.lock")}
        path: .venv
    - if: steps.cached-poetry-dependencies.outputs.cache-hit != "true"
      name: Install dependencies
      run: poetry install --no-interaction --no-root
    - name: Install project
      run: poetry install --no-interaction
    - name: Run tests for job 3
      run: 'poetry run pytest '
  test-group-4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - id: cached-poetry-dependencies
      name: Load cached venv
      uses: actions/cache@v3
      with:
        key: venv-{"runner.os"}-{"steps.setup-python.outputs.python-version"}-{"hashFiles("**/poetry.lock")}
        path: .venv
    - if: steps.cached-poetry-dependencies.outputs.cache-hit != "true"
      name: Install dependencies
      run: poetry install --no-interaction --no-root
    - name: Install project
      run: poetry install --no-interaction
    - name: Run tests for job 4
      run: 'poetry run pytest '
name: Parallel Tests
'on':
- push
- pull_request
